version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: mymentor_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mymentorpassword
      POSTGRES_DB: mymentor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: mymentor_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:mymentorpassword@db:5432/mymentor
      - PORT=8000
      - UPLOAD_FOLDER=/app/uploads
      - JWT_SECRET=c1a93bd8c8a14b3da5cb2db55de31d75c9428c89c8a914ba1d6a9a01f7051bc2
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
